package domain

var Permissions = map[string]int64{
    "read_comments"   : 1 << 0,
	"write_comments"  : 1 << 1,
    "edit_comments"   : 1 << 2,
    "delete_comments" : 1 << 3,
    "read_chat"       : 1 << 4,
    "write_chat"      : 1 << 5,
    "edit_chat"       : 1 << 6,
    "delete_chat"     : 1 << 7,
    "read_video"      : 1 << 8,
    "write_video"     : 1 << 9,
    "edit_video"      : 1 << 10,
    "delete_video"    : 1 << 11,
    "read_image"      : 1 << 12,
    "write_image"     : 1 << 13,
    "edit_image"      : 1 << 14,
    "delete_image"    : 1 << 15,
    "read_channel"    : 1 << 16,
    "edit_channel"    : 1 << 17,
    "write_channel"   : 1 << 18,
    "delete_channel"  : 1 << 19,
    "read_roles"      : 1 << 20,
    "edit_roles"      : 1 << 21,
    "write_roles"     : 1 << 22,
    "delete_roles"    : 1 << 23,
    "admin"           : 1 << 24,
    "administrator"   : 1 << 25,
}
